{% set name = "cf-units" %}
{% set version = "3.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name.replace('_', '-') }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2327da492f30cf018a3f1b5950192ce9bb3332e50b1c7ac53f7543de7fa61fdb

build:
  number: 0
  skip: True  # [py<310]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - pip
    - numpy
    - cython
    - udunits2
    - setuptools
    - setuptools-scm
  run:
    - {{ pin_compatible('udunits2', max_pin='x.x') }}
    - python
    - cftime >=1.5.2
    - jinja2

test:
  requires:
    - pytest
    - pip
  imports:
    - cf_units
  commands:
    - pip check
    - pytest --pyargs cf_units

about:
  home: https://cf-units.readthedocs.io/en/latest/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Units of measure as required by the Climate and Forecast (CF) Metadata Conventions.

extra:
  recipe-maintainers:
    - bjlittle
    - ocefpaf
    - pelson
    - trexfeathers
    - pp-mo
